# Generated by Django 3.1.7 on 2021-03-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_auto_20210302_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='lista_sentimentos',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
