# Generated by Django 3.1.7 on 2021-03-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_auto_20210302_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='lista_sentimentos',
            field=models.TextField(null=True),
        ),
    ]
